/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.NewUserController;
import dao.UserDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Formation
 */
public class NewUserView extends javax.swing.JPanel {

    /**
     * Creates new form NewUserView
     */
    public NewUserView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Pseudo = new javax.swing.JLabel();
        PseudoTextField = new javax.swing.JTextField();
        Lastname = new javax.swing.JLabel();
        LastnameTextField = new javax.swing.JTextField();
        Firstname = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        Password = new javax.swing.JLabel();
        FirstnameTextField = new javax.swing.JTextField();
        Mail = new javax.swing.JLabel();
        MailTextField = new javax.swing.JTextField();
        Inscription = new javax.swing.JLabel();
        WelcomeIcon = new javax.swing.JLabel();
        CGU = new javax.swing.JCheckBox();
        Connexion = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        Pseudo.setText("Pseudo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(9, 363, 0, 37);
        jPanel1.add(Pseudo, gridBagConstraints);

        PseudoTextField.setText("jTextField1");
        PseudoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 8);
        jPanel1.add(PseudoTextField, gridBagConstraints);

        Lastname.setText("Nom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 363, 7, 37);
        jPanel1.add(Lastname, gridBagConstraints);

        LastnameTextField.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 7, 8);
        jPanel1.add(LastnameTextField, gridBagConstraints);

        Firstname.setText("Prénom");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(9, 363, 7, 37);
        jPanel1.add(Firstname, gridBagConstraints);

        PasswordField.setText("jPasswordField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 8);
        jPanel1.add(PasswordField, gridBagConstraints);

        Password.setText("Mot de passe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(7, 363, 0, 37);
        jPanel1.add(Password, gridBagConstraints);

        FirstnameTextField.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 7, 8);
        jPanel1.add(FirstnameTextField, gridBagConstraints);

        Mail.setText("@Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(6, 363, 0, 37);
        jPanel1.add(Mail, gridBagConstraints);

        MailTextField.setText("jTextField4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 8);
        jPanel1.add(MailTextField, gridBagConstraints);

        Inscription.setText("Inscription");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 0);
        jPanel1.add(Inscription, gridBagConstraints);

        WelcomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/38671158-freeze-wallpapers.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 2, 0);
        jPanel1.add(WelcomeIcon, gridBagConstraints);

        CGU.setText("J'accepte les Conditions Générales d'Utilisation");
        CGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGUActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 60, 0, 0);
        jPanel1.add(CGU, gridBagConstraints);

        Connexion.setText("Connexion");
        Connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnexionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 42, 0, 0);
        jPanel1.add(Connexion, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void CGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGUActionPerformed

    private void ConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnexionActionPerformed
        // TODO add your handling code here:
        
    PseudoTextField.setText("");
    LastnameTextField.setText("");
    FirstnameTextField.setText("");
    PasswordField.setText("");
    MailTextField.setText("");
    
    boolean result = newUserController.CreateNewUser(this);
   
   // if all complete
   if(result){
        
        
        JOptionPane info = new JOptionPane();
        
        info.showMessageDialog(this, 
                "l'utilisateur est créé",
                "information",
                JOptionPane.WARNING_MESSAGE);
   }else{
        
    // if a field is empty    
        JOptionPane alert = new JOptionPane();
    
        alert.showMessageDialog(this,
        "Un champ de creation n'est pas rempli",
        "attention",
        JOptionPane.WARNING_MESSAGE);
   }
    
                                  
    }//GEN-LAST:event_ConnexionActionPerformed

    private void PseudoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PseudoTextFieldActionPerformed

  //------------------------------------------------------------------------------
    //button create user
                                         

        
    
//------------------------------------------------------------------------------
    //empty input 
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
       
   
    }                                         
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CGU;
    private javax.swing.JButton Connexion;
    private javax.swing.JLabel Firstname;
    private javax.swing.JTextField FirstnameTextField;
    private javax.swing.JLabel Inscription;
    private javax.swing.JLabel Lastname;
    private javax.swing.JTextField LastnameTextField;
    private javax.swing.JLabel Mail;
    private javax.swing.JTextField MailTextField;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Pseudo;
    private javax.swing.JTextField PseudoTextField;
    private javax.swing.JLabel WelcomeIcon;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JTextField getPseudoTextField() {
        return PseudoTextField;  
    }

    public JTextField getLastnameTextField() {
        return LastnameTextField;
    }

    public JTextField getFirstnameTextField() {
        return FirstnameTextField;
    }
    
    public Object getPasswordTextField() {
        return PasswordField;
    }

    public JTextField getMailTextField() {
        return MailTextField;
    }
}
